/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AddMediaProgressRequest
 */
export interface AddMediaProgressRequest {
    /**
     * 
     * @type {string}
     * @memberof AddMediaProgressRequest
     */
    requestSource?: string;
    /**
     * 
     * @type {string}
     * @memberof AddMediaProgressRequest
     */
    providedUrl?: string;
}

/**
 * Check if a given object implements the AddMediaProgressRequest interface.
 */
export function instanceOfAddMediaProgressRequest(value: object): value is AddMediaProgressRequest {
    return true;
}

export function AddMediaProgressRequestFromJSON(json: any): AddMediaProgressRequest {
    return AddMediaProgressRequestFromJSONTyped(json, false);
}

export function AddMediaProgressRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): AddMediaProgressRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'requestSource': json['requestSource'] == null ? undefined : json['requestSource'],
        'providedUrl': json['provided_url'] == null ? undefined : json['provided_url'],
    };
}

export function AddMediaProgressRequestToJSON(json: any): AddMediaProgressRequest {
    return AddMediaProgressRequestToJSONTyped(json, false);
}

export function AddMediaProgressRequestToJSONTyped(value?: AddMediaProgressRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'requestSource': value['requestSource'],
        'provided_url': value['providedUrl'],
    };
}

