/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AddUserSubmissionRequest
 */
export interface AddUserSubmissionRequest {
    /**
     * 
     * @type {string}
     * @memberof AddUserSubmissionRequest
     */
    submissionType?: AddUserSubmissionRequestSubmissionTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof AddUserSubmissionRequest
     */
    description?: string;
}


/**
 * @export
 */
export const AddUserSubmissionRequestSubmissionTypeEnum = {
    Support: 'SUPPORT',
    Bug: 'BUG',
    FeatureRequest: 'FEATURE_REQUEST',
    Review: 'REVIEW',
    Misc: 'MISC'
} as const;
export type AddUserSubmissionRequestSubmissionTypeEnum = typeof AddUserSubmissionRequestSubmissionTypeEnum[keyof typeof AddUserSubmissionRequestSubmissionTypeEnum];


/**
 * Check if a given object implements the AddUserSubmissionRequest interface.
 */
export function instanceOfAddUserSubmissionRequest(value: object): value is AddUserSubmissionRequest {
    return true;
}

export function AddUserSubmissionRequestFromJSON(json: any): AddUserSubmissionRequest {
    return AddUserSubmissionRequestFromJSONTyped(json, false);
}

export function AddUserSubmissionRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): AddUserSubmissionRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'submissionType': json['submissionType'] == null ? undefined : json['submissionType'],
        'description': json['description'] == null ? undefined : json['description'],
    };
}

export function AddUserSubmissionRequestToJSON(json: any): AddUserSubmissionRequest {
    return AddUserSubmissionRequestToJSONTyped(json, false);
}

export function AddUserSubmissionRequestToJSONTyped(value?: AddUserSubmissionRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'submissionType': value['submissionType'],
        'description': value['description'],
    };
}

