/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DeleteTrackedMediaRequest
 */
export interface DeleteTrackedMediaRequest {
    /**
     * 
     * @type {number}
     * @memberof DeleteTrackedMediaRequest
     */
    mediaId?: number;
}

/**
 * Check if a given object implements the DeleteTrackedMediaRequest interface.
 */
export function instanceOfDeleteTrackedMediaRequest(value: object): value is DeleteTrackedMediaRequest {
    return true;
}

export function DeleteTrackedMediaRequestFromJSON(json: any): DeleteTrackedMediaRequest {
    return DeleteTrackedMediaRequestFromJSONTyped(json, false);
}

export function DeleteTrackedMediaRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): DeleteTrackedMediaRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'mediaId': json['media_id'] == null ? undefined : json['media_id'],
    };
}

export function DeleteTrackedMediaRequestToJSON(json: any): DeleteTrackedMediaRequest {
    return DeleteTrackedMediaRequestToJSONTyped(json, false);
}

export function DeleteTrackedMediaRequestToJSONTyped(value?: DeleteTrackedMediaRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'media_id': value['mediaId'],
    };
}

