/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface EmailLoginRequest
 */
export interface EmailLoginRequest {
    /**
     * 
     * @type {string}
     * @memberof EmailLoginRequest
     */
    loginToken?: string;
}

/**
 * Check if a given object implements the EmailLoginRequest interface.
 */
export function instanceOfEmailLoginRequest(value: object): value is EmailLoginRequest {
    return true;
}

export function EmailLoginRequestFromJSON(json: any): EmailLoginRequest {
    return EmailLoginRequestFromJSONTyped(json, false);
}

export function EmailLoginRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): EmailLoginRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'loginToken': json['login_token'] == null ? undefined : json['login_token'],
    };
}

export function EmailLoginRequestToJSON(json: any): EmailLoginRequest {
    return EmailLoginRequestToJSONTyped(json, false);
}

export function EmailLoginRequestToJSONTyped(value?: EmailLoginRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'login_token': value['loginToken'],
    };
}

