/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { MediaDto } from './MediaDto';
import {
    MediaDtoFromJSON,
    MediaDtoFromJSONTyped,
    MediaDtoToJSON,
    MediaDtoToJSONTyped,
} from './MediaDto';
import type { MediaProgressDto } from './MediaProgressDto';
import {
    MediaProgressDtoFromJSON,
    MediaProgressDtoFromJSONTyped,
    MediaProgressDtoToJSON,
    MediaProgressDtoToJSONTyped,
} from './MediaProgressDto';
import type { MediaSiteWithMediaUrlDto } from './MediaSiteWithMediaUrlDto';
import {
    MediaSiteWithMediaUrlDtoFromJSON,
    MediaSiteWithMediaUrlDtoFromJSONTyped,
    MediaSiteWithMediaUrlDtoToJSON,
    MediaSiteWithMediaUrlDtoToJSONTyped,
} from './MediaSiteWithMediaUrlDto';

/**
 * 
 * @export
 * @interface MediaWithProgressesAndSitesDto
 */
export interface MediaWithProgressesAndSitesDto {
    /**
     * 
     * @type {MediaDto}
     * @memberof MediaWithProgressesAndSitesDto
     */
    media?: MediaDto;
    /**
     * 
     * @type {Array<MediaProgressDto>}
     * @memberof MediaWithProgressesAndSitesDto
     */
    mediaProgresses?: Array<MediaProgressDto>;
    /**
     * 
     * @type {Array<MediaSiteWithMediaUrlDto>}
     * @memberof MediaWithProgressesAndSitesDto
     */
    mediaSitesWithUrls?: Array<MediaSiteWithMediaUrlDto>;
}

/**
 * Check if a given object implements the MediaWithProgressesAndSitesDto interface.
 */
export function instanceOfMediaWithProgressesAndSitesDto(value: object): value is MediaWithProgressesAndSitesDto {
    return true;
}

export function MediaWithProgressesAndSitesDtoFromJSON(json: any): MediaWithProgressesAndSitesDto {
    return MediaWithProgressesAndSitesDtoFromJSONTyped(json, false);
}

export function MediaWithProgressesAndSitesDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): MediaWithProgressesAndSitesDto {
    if (json == null) {
        return json;
    }
    return {
        
        'media': json['media'] == null ? undefined : MediaDtoFromJSON(json['media']),
        'mediaProgresses': json['mediaProgresses'] == null ? undefined : ((json['mediaProgresses'] as Array<any>).map(MediaProgressDtoFromJSON)),
        'mediaSitesWithUrls': json['mediaSitesWithUrls'] == null ? undefined : ((json['mediaSitesWithUrls'] as Array<any>).map(MediaSiteWithMediaUrlDtoFromJSON)),
    };
}

export function MediaWithProgressesAndSitesDtoToJSON(json: any): MediaWithProgressesAndSitesDto {
    return MediaWithProgressesAndSitesDtoToJSONTyped(json, false);
}

export function MediaWithProgressesAndSitesDtoToJSONTyped(value?: MediaWithProgressesAndSitesDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'media': MediaDtoToJSON(value['media']),
        'mediaProgresses': value['mediaProgresses'] == null ? undefined : ((value['mediaProgresses'] as Array<any>).map(MediaProgressDtoToJSON)),
        'mediaSitesWithUrls': value['mediaSitesWithUrls'] == null ? undefined : ((value['mediaSitesWithUrls'] as Array<any>).map(MediaSiteWithMediaUrlDtoToJSON)),
    };
}

