/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface MediaProgressId
 */
export interface MediaProgressId {
    /**
     * 
     * @type {number}
     * @memberof MediaProgressId
     */
    userId?: number;
    /**
     * 
     * @type {string}
     * @memberof MediaProgressId
     */
    recentChapterUrl?: string;
}

/**
 * Check if a given object implements the MediaProgressId interface.
 */
export function instanceOfMediaProgressId(value: object): value is MediaProgressId {
    return true;
}

export function MediaProgressIdFromJSON(json: any): MediaProgressId {
    return MediaProgressIdFromJSONTyped(json, false);
}

export function MediaProgressIdFromJSONTyped(json: any, ignoreDiscriminator: boolean): MediaProgressId {
    if (json == null) {
        return json;
    }
    return {
        
        'userId': json['userId'] == null ? undefined : json['userId'],
        'recentChapterUrl': json['recentChapterUrl'] == null ? undefined : json['recentChapterUrl'],
    };
}

export function MediaProgressIdToJSON(json: any): MediaProgressId {
    return MediaProgressIdToJSONTyped(json, false);
}

export function MediaProgressIdToJSONTyped(value?: MediaProgressId | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'userId': value['userId'],
        'recentChapterUrl': value['recentChapterUrl'],
    };
}

