/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { MediaSiteDto } from './MediaSiteDto';
import {
    MediaSiteDtoFromJSON,
    MediaSiteDtoFromJSONTyped,
    MediaSiteDtoToJSON,
    MediaSiteDtoToJSONTyped,
} from './MediaSiteDto';

/**
 * 
 * @export
 * @interface MediaSiteWithMediaUrlDto
 */
export interface MediaSiteWithMediaUrlDto {
    /**
     * 
     * @type {MediaSiteDto}
     * @memberof MediaSiteWithMediaUrlDto
     */
    mediaSite?: MediaSiteDto;
    /**
     * 
     * @type {string}
     * @memberof MediaSiteWithMediaUrlDto
     */
    baseUrl?: string;
}

/**
 * Check if a given object implements the MediaSiteWithMediaUrlDto interface.
 */
export function instanceOfMediaSiteWithMediaUrlDto(value: object): value is MediaSiteWithMediaUrlDto {
    return true;
}

export function MediaSiteWithMediaUrlDtoFromJSON(json: any): MediaSiteWithMediaUrlDto {
    return MediaSiteWithMediaUrlDtoFromJSONTyped(json, false);
}

export function MediaSiteWithMediaUrlDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): MediaSiteWithMediaUrlDto {
    if (json == null) {
        return json;
    }
    return {
        
        'mediaSite': json['mediaSite'] == null ? undefined : MediaSiteDtoFromJSON(json['mediaSite']),
        'baseUrl': json['baseUrl'] == null ? undefined : json['baseUrl'],
    };
}

export function MediaSiteWithMediaUrlDtoToJSON(json: any): MediaSiteWithMediaUrlDto {
    return MediaSiteWithMediaUrlDtoToJSONTyped(json, false);
}

export function MediaSiteWithMediaUrlDtoToJSONTyped(value?: MediaSiteWithMediaUrlDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'mediaSite': MediaSiteDtoToJSON(value['mediaSite']),
        'baseUrl': value['baseUrl'],
    };
}

