/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface MediaProgressDto
 */
export interface MediaProgressDto {
    /**
     * 
     * @type {number}
     * @memberof MediaProgressDto
     */
    userId?: number;
    /**
     * 
     * @type {string}
     * @memberof MediaProgressDto
     */
    recentChapterUrl?: string;
    /**
     * 
     * @type {number}
     * @memberof MediaProgressDto
     */
    mediaId?: number;
    /**
     * 
     * @type {string}
     * @memberof MediaProgressDto
     */
    chapterNumber?: string;
    /**
     * 
     * @type {string}
     * @memberof MediaProgressDto
     */
    status?: MediaProgressDtoStatusEnum;
    /**
     * 
     * @type {Date}
     * @memberof MediaProgressDto
     */
    createdAt?: Date;
    /**
     * 
     * @type {Date}
     * @memberof MediaProgressDto
     */
    lastUpdatedAt?: Date;
}


/**
 * @export
 */
export const MediaProgressDtoStatusEnum = {
    InProgress: 'In Progress',
    Read: 'Read',
    ReRead: 'Re-Read'
} as const;
export type MediaProgressDtoStatusEnum = typeof MediaProgressDtoStatusEnum[keyof typeof MediaProgressDtoStatusEnum];


/**
 * Check if a given object implements the MediaProgressDto interface.
 */
export function instanceOfMediaProgressDto(value: object): value is MediaProgressDto {
    return true;
}

export function MediaProgressDtoFromJSON(json: any): MediaProgressDto {
    return MediaProgressDtoFromJSONTyped(json, false);
}

export function MediaProgressDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): MediaProgressDto {
    if (json == null) {
        return json;
    }
    return {
        
        'userId': json['userId'] == null ? undefined : json['userId'],
        'recentChapterUrl': json['recentChapterUrl'] == null ? undefined : json['recentChapterUrl'],
        'mediaId': json['mediaId'] == null ? undefined : json['mediaId'],
        'chapterNumber': json['chapterNumber'] == null ? undefined : json['chapterNumber'],
        'status': json['status'] == null ? undefined : json['status'],
        'createdAt': json['createdAt'] == null ? undefined : (new Date(json['createdAt'])),
        'lastUpdatedAt': json['lastUpdatedAt'] == null ? undefined : (new Date(json['lastUpdatedAt'])),
    };
}

export function MediaProgressDtoToJSON(json: any): MediaProgressDto {
    return MediaProgressDtoToJSONTyped(json, false);
}

export function MediaProgressDtoToJSONTyped(value?: MediaProgressDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'userId': value['userId'],
        'recentChapterUrl': value['recentChapterUrl'],
        'mediaId': value['mediaId'],
        'chapterNumber': value['chapterNumber'],
        'status': value['status'],
        'createdAt': value['createdAt'] == null ? value['createdAt'] : value['createdAt'].toISOString(),
        'lastUpdatedAt': value['lastUpdatedAt'] == null ? value['lastUpdatedAt'] : value['lastUpdatedAt'].toISOString(),
    };
}

