/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface MediaSiteDto
 */
export interface MediaSiteDto {
    /**
     * 
     * @type {number}
     * @memberof MediaSiteDto
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof MediaSiteDto
     */
    siteName?: string;
    /**
     * 
     * @type {string}
     * @memberof MediaSiteDto
     */
    urlPrefix?: string;
    /**
     * 
     * @type {string}
     * @memberof MediaSiteDto
     */
    siteStatus?: MediaSiteDtoSiteStatusEnum;
    /**
     * 
     * @type {boolean}
     * @memberof MediaSiteDto
     */
    primarySource?: boolean;
}


/**
 * @export
 */
export const MediaSiteDtoSiteStatusEnum = {
    NotReviewed: 'NOT_REVIEWED',
    Approved: 'APPROVED',
    Denied: 'DENIED',
    Banned: 'BANNED',
    Ineligible: 'INELIGIBLE'
} as const;
export type MediaSiteDtoSiteStatusEnum = typeof MediaSiteDtoSiteStatusEnum[keyof typeof MediaSiteDtoSiteStatusEnum];


/**
 * Check if a given object implements the MediaSiteDto interface.
 */
export function instanceOfMediaSiteDto(value: object): value is MediaSiteDto {
    return true;
}

export function MediaSiteDtoFromJSON(json: any): MediaSiteDto {
    return MediaSiteDtoFromJSONTyped(json, false);
}

export function MediaSiteDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): MediaSiteDto {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'siteName': json['siteName'] == null ? undefined : json['siteName'],
        'urlPrefix': json['urlPrefix'] == null ? undefined : json['urlPrefix'],
        'siteStatus': json['siteStatus'] == null ? undefined : json['siteStatus'],
        'primarySource': json['primarySource'] == null ? undefined : json['primarySource'],
    };
}

export function MediaSiteDtoToJSON(json: any): MediaSiteDto {
    return MediaSiteDtoToJSONTyped(json, false);
}

export function MediaSiteDtoToJSONTyped(value?: MediaSiteDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'siteName': value['siteName'],
        'urlPrefix': value['urlPrefix'],
        'siteStatus': value['siteStatus'],
        'primarySource': value['primarySource'],
    };
}

