/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface MediaDto
 */
export interface MediaDto {
    /**
     * 
     * @type {number}
     * @memberof MediaDto
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof MediaDto
     */
    title?: string;
    /**
     * 
     * @type {string}
     * @memberof MediaDto
     */
    description?: string;
    /**
     * 
     * @type {string}
     * @memberof MediaDto
     */
    imageUrl?: string;
    /**
     * 
     * @type {string}
     * @memberof MediaDto
     */
    type?: MediaDtoTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof MediaDto
     */
    status?: MediaDtoStatusEnum;
    /**
     * 
     * @type {string}
     * @memberof MediaDto
     */
    latestChapter?: string;
    /**
     * 
     * @type {Date}
     * @memberof MediaDto
     */
    createdAt?: Date;
    /**
     * 
     * @type {Date}
     * @memberof MediaDto
     */
    lastUpdatedAt?: Date;
    /**
     * 
     * @type {Date}
     * @memberof MediaDto
     */
    enrichedAt?: Date;
}


/**
 * @export
 */
export const MediaDtoTypeEnum = {
    Manga: 'Manga',
    Manhwa: 'Manhwa',
    LightNovel: 'Light Novel',
    Webtoon: 'Webtoon',
    Manhua: 'Manhua',
    Novel: 'Novel',
    Comic: 'Comic',
    Other: 'Other'
} as const;
export type MediaDtoTypeEnum = typeof MediaDtoTypeEnum[keyof typeof MediaDtoTypeEnum];

/**
 * @export
 */
export const MediaDtoStatusEnum = {
    Ongoing: 'ONGOING',
    Completed: 'COMPLETED',
    Hiatus: 'HIATUS',
    Cancelled: 'CANCELLED',
    Unknown: 'UNKNOWN'
} as const;
export type MediaDtoStatusEnum = typeof MediaDtoStatusEnum[keyof typeof MediaDtoStatusEnum];


/**
 * Check if a given object implements the MediaDto interface.
 */
export function instanceOfMediaDto(value: object): value is MediaDto {
    return true;
}

export function MediaDtoFromJSON(json: any): MediaDto {
    return MediaDtoFromJSONTyped(json, false);
}

export function MediaDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): MediaDto {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'title': json['title'] == null ? undefined : json['title'],
        'description': json['description'] == null ? undefined : json['description'],
        'imageUrl': json['imageUrl'] == null ? undefined : json['imageUrl'],
        'type': json['type'] == null ? undefined : json['type'],
        'status': json['status'] == null ? undefined : json['status'],
        'latestChapter': json['latestChapter'] == null ? undefined : json['latestChapter'],
        'createdAt': json['createdAt'] == null ? undefined : (new Date(json['createdAt'])),
        'lastUpdatedAt': json['lastUpdatedAt'] == null ? undefined : (new Date(json['lastUpdatedAt'])),
        'enrichedAt': json['enrichedAt'] == null ? undefined : (new Date(json['enrichedAt'])),
    };
}

export function MediaDtoToJSON(json: any): MediaDto {
    return MediaDtoToJSONTyped(json, false);
}

export function MediaDtoToJSONTyped(value?: MediaDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'title': value['title'],
        'description': value['description'],
        'imageUrl': value['imageUrl'],
        'type': value['type'],
        'status': value['status'],
        'latestChapter': value['latestChapter'],
        'createdAt': value['createdAt'] == null ? value['createdAt'] : value['createdAt'].toISOString(),
        'lastUpdatedAt': value['lastUpdatedAt'] == null ? value['lastUpdatedAt'] : value['lastUpdatedAt'].toISOString(),
        'enrichedAt': value['enrichedAt'] == null ? value['enrichedAt'] : value['enrichedAt'].toISOString(),
    };
}

