/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { MediaDto } from './MediaDto';
import {
    MediaDtoFromJSON,
    MediaDtoFromJSONTyped,
    MediaDtoToJSON,
    MediaDtoToJSONTyped,
} from './MediaDto';
import type { MediaProgressDto } from './MediaProgressDto';
import {
    MediaProgressDtoFromJSON,
    MediaProgressDtoFromJSONTyped,
    MediaProgressDtoToJSON,
    MediaProgressDtoToJSONTyped,
} from './MediaProgressDto';

/**
 * 
 * @export
 * @interface MediaWithProgressDto
 */
export interface MediaWithProgressDto {
    /**
     * 
     * @type {MediaDto}
     * @memberof MediaWithProgressDto
     */
    media?: MediaDto;
    /**
     * 
     * @type {MediaProgressDto}
     * @memberof MediaWithProgressDto
     */
    mediaProgress?: MediaProgressDto;
}

/**
 * Check if a given object implements the MediaWithProgressDto interface.
 */
export function instanceOfMediaWithProgressDto(value: object): value is MediaWithProgressDto {
    return true;
}

export function MediaWithProgressDtoFromJSON(json: any): MediaWithProgressDto {
    return MediaWithProgressDtoFromJSONTyped(json, false);
}

export function MediaWithProgressDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): MediaWithProgressDto {
    if (json == null) {
        return json;
    }
    return {
        
        'media': json['media'] == null ? undefined : MediaDtoFromJSON(json['media']),
        'mediaProgress': json['mediaProgress'] == null ? undefined : MediaProgressDtoFromJSON(json['mediaProgress']),
    };
}

export function MediaWithProgressDtoToJSON(json: any): MediaWithProgressDto {
    return MediaWithProgressDtoToJSONTyped(json, false);
}

export function MediaWithProgressDtoToJSONTyped(value?: MediaWithProgressDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'media': MediaDtoToJSON(value['media']),
        'mediaProgress': MediaProgressDtoToJSON(value['mediaProgress']),
    };
}

