/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { MediaProgressId } from './MediaProgressId';
import {
    MediaProgressIdFromJSON,
    MediaProgressIdFromJSONTyped,
    MediaProgressIdToJSON,
    MediaProgressIdToJSONTyped,
} from './MediaProgressId';

/**
 * 
 * @export
 * @interface MediaMergeRequest
 */
export interface MediaMergeRequest {
    /**
     * 
     * @type {MediaProgressId}
     * @memberof MediaMergeRequest
     */
    mediaProgressToMergeID?: MediaProgressId;
}

/**
 * Check if a given object implements the MediaMergeRequest interface.
 */
export function instanceOfMediaMergeRequest(value: object): value is MediaMergeRequest {
    return true;
}

export function MediaMergeRequestFromJSON(json: any): MediaMergeRequest {
    return MediaMergeRequestFromJSONTyped(json, false);
}

export function MediaMergeRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): MediaMergeRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'mediaProgressToMergeID': json['mediaProgressToMergeID'] == null ? undefined : MediaProgressIdFromJSON(json['mediaProgressToMergeID']),
    };
}

export function MediaMergeRequestToJSON(json: any): MediaMergeRequest {
    return MediaMergeRequestToJSONTyped(json, false);
}

export function MediaMergeRequestToJSONTyped(value?: MediaMergeRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'mediaProgressToMergeID': MediaProgressIdToJSON(value['mediaProgressToMergeID']),
    };
}

