/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SendEmailLoginLinkRequest
 */
export interface SendEmailLoginLinkRequest {
    /**
     * 
     * @type {string}
     * @memberof SendEmailLoginLinkRequest
     */
    email?: string;
}

/**
 * Check if a given object implements the SendEmailLoginLinkRequest interface.
 */
export function instanceOfSendEmailLoginLinkRequest(value: object): value is SendEmailLoginLinkRequest {
    return true;
}

export function SendEmailLoginLinkRequestFromJSON(json: any): SendEmailLoginLinkRequest {
    return SendEmailLoginLinkRequestFromJSONTyped(json, false);
}

export function SendEmailLoginLinkRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): SendEmailLoginLinkRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'email': json['email'] == null ? undefined : json['email'],
    };
}

export function SendEmailLoginLinkRequestToJSON(json: any): SendEmailLoginLinkRequest {
    return SendEmailLoginLinkRequestToJSONTyped(json, false);
}

export function SendEmailLoginLinkRequestToJSONTyped(value?: SendEmailLoginLinkRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'email': value['email'],
    };
}

