/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Represents a user notification
 * @export
 * @interface UserNotificationDto
 */
export interface UserNotificationDto {
    /**
     * Notification ID
     * @type {number}
     * @memberof UserNotificationDto
     */
    id?: number;
    /**
     * ID of the user this notification belongs to
     * @type {number}
     * @memberof UserNotificationDto
     */
    userId?: number;
    /**
     * Notification message content
     * @type {string}
     * @memberof UserNotificationDto
     */
    message?: string;
    /**
     * Type of notification
     * @type {string}
     * @memberof UserNotificationDto
     */
    type?: UserNotificationDtoTypeEnum;
    /**
     * Read/unread status of the notification
     * @type {string}
     * @memberof UserNotificationDto
     */
    status?: UserNotificationDtoStatusEnum;
    /**
     * Result of the notification action
     * @type {string}
     * @memberof UserNotificationDto
     */
    result?: UserNotificationDtoResultEnum;
    /**
     * Timestamp when the notification was created
     * @type {Date}
     * @memberof UserNotificationDto
     */
    createdAt?: Date;
}


/**
 * @export
 */
export const UserNotificationDtoTypeEnum = {
    ProgressUploadSuccess: 'PROGRESS_UPLOAD_SUCCESS',
    ProgressUploadFailure: 'PROGRESS_UPLOAD_FAILURE'
} as const;
export type UserNotificationDtoTypeEnum = typeof UserNotificationDtoTypeEnum[keyof typeof UserNotificationDtoTypeEnum];

/**
 * @export
 */
export const UserNotificationDtoStatusEnum = {
    Unread: 'UNREAD',
    Read: 'READ'
} as const;
export type UserNotificationDtoStatusEnum = typeof UserNotificationDtoStatusEnum[keyof typeof UserNotificationDtoStatusEnum];

/**
 * @export
 */
export const UserNotificationDtoResultEnum = {
    Success: 'Success',
    Failure: 'Failure'
} as const;
export type UserNotificationDtoResultEnum = typeof UserNotificationDtoResultEnum[keyof typeof UserNotificationDtoResultEnum];


/**
 * Check if a given object implements the UserNotificationDto interface.
 */
export function instanceOfUserNotificationDto(value: object): value is UserNotificationDto {
    return true;
}

export function UserNotificationDtoFromJSON(json: any): UserNotificationDto {
    return UserNotificationDtoFromJSONTyped(json, false);
}

export function UserNotificationDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserNotificationDto {
    if (json == null) {
        return json;
    }
    return {

        'id': json['id'] == null ? undefined : json['id'],
        'userId': json['userId'] == null ? undefined : json['userId'],
        'message': json['message'] == null ? undefined : json['message'],
        'type': json['type'] == null ? undefined : json['type'],
        'status': json['status'] == null ? undefined : json['status'],
        'result': json['result'] == null ? undefined : json['result'],
        'createdAt': json['createdAt'] == null ? undefined : (new Date(json['createdAt'])),
    };
}

export function UserNotificationDtoToJSON(json: any): UserNotificationDto {
    return UserNotificationDtoToJSONTyped(json, false);
}

export function UserNotificationDtoToJSONTyped(value?: UserNotificationDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'id': value['id'],
        'userId': value['userId'],
        'message': value['message'],
        'type': value['type'],
        'status': value['status'],
        'result': value['result'],
        'createdAt': value['createdAt'] == null ? value['createdAt'] : value['createdAt'].toISOString(),
    };
}
