/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { UserNotificationDto } from './UserNotificationDto';
import {
    UserNotificationDtoFromJSON,
    UserNotificationDtoFromJSONTyped,
    UserNotificationDtoToJSON,
    UserNotificationDtoToJSONTyped,
} from './UserNotificationDto';

/**
 * Paginated list of user notifications
 * @export
 * @interface UserNotificationListDto
 */
export interface UserNotificationListDto {
    /**
     * Current page number
     * @type {number}
     * @memberof UserNotificationListDto
     */
    page?: number;
    /**
     * List of user notifications
     * @type {Array<UserNotificationDto>}
     * @memberof UserNotificationListDto
     */
    notifications?: Array<UserNotificationDto>;
}

/**
 * Check if a given object implements the UserNotificationListDto interface.
 */
export function instanceOfUserNotificationListDto(value: object): value is UserNotificationListDto {
    return true;
}

export function UserNotificationListDtoFromJSON(json: any): UserNotificationListDto {
    return UserNotificationListDtoFromJSONTyped(json, false);
}

export function UserNotificationListDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserNotificationListDto {
    if (json == null) {
        return json;
    }
    return {
        
        'page': json['page'] == null ? undefined : json['page'],
        'notifications': json['notifications'] == null ? undefined : ((json['notifications'] as Array<any>).map(UserNotificationDtoFromJSON)),
    };
}

export function UserNotificationListDtoToJSON(json: any): UserNotificationListDto {
    return UserNotificationListDtoToJSONTyped(json, false);
}

export function UserNotificationListDtoToJSONTyped(value?: UserNotificationListDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'page': value['page'],
        'notifications': value['notifications'] == null ? undefined : ((value['notifications'] as Array<any>).map(UserNotificationDtoToJSON)),
    };
}

