/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ValidateIsEligibleSiteResponse
 */
export interface ValidateIsEligibleSiteResponse {
    /**
     * 
     * @type {string}
     * @memberof ValidateIsEligibleSiteResponse
     */
    baseUrl?: string;
    /**
     * 
     * @type {string}
     * @memberof ValidateIsEligibleSiteResponse
     */
    canTrackStatus?: ValidateIsEligibleSiteResponseCanTrackStatusEnum;
    /**
     * 
     * @type {string}
     * @memberof ValidateIsEligibleSiteResponse
     */
    errMsg?: string;
}


/**
 * @export
 */
export const ValidateIsEligibleSiteResponseCanTrackStatusEnum = {
    CanTrack: 'CAN_TRACK',
    CannotTrack: 'CANNOT_TRACK'
} as const;
export type ValidateIsEligibleSiteResponseCanTrackStatusEnum = typeof ValidateIsEligibleSiteResponseCanTrackStatusEnum[keyof typeof ValidateIsEligibleSiteResponseCanTrackStatusEnum];


/**
 * Check if a given object implements the ValidateIsEligibleSiteResponse interface.
 */
export function instanceOfValidateIsEligibleSiteResponse(value: object): value is ValidateIsEligibleSiteResponse {
    return true;
}

export function ValidateIsEligibleSiteResponseFromJSON(json: any): ValidateIsEligibleSiteResponse {
    return ValidateIsEligibleSiteResponseFromJSONTyped(json, false);
}

export function ValidateIsEligibleSiteResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ValidateIsEligibleSiteResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'baseUrl': json['baseUrl'] == null ? undefined : json['baseUrl'],
        'canTrackStatus': json['canTrackStatus'] == null ? undefined : json['canTrackStatus'],
        'errMsg': json['errMsg'] == null ? undefined : json['errMsg'],
    };
}

export function ValidateIsEligibleSiteResponseToJSON(json: any): ValidateIsEligibleSiteResponse {
    return ValidateIsEligibleSiteResponseToJSONTyped(json, false);
}

export function ValidateIsEligibleSiteResponseToJSONTyped(value?: ValidateIsEligibleSiteResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'baseUrl': value['baseUrl'],
        'canTrackStatus': value['canTrackStatus'],
        'errMsg': value['errMsg'],
    };
}

