/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  MediaMergeRequest,
} from '../models/index';
import {
    MediaMergeRequestFromJSON,
    MediaMergeRequestToJSON,
} from '../models/index';

export interface AddNewMediaProgressRequest {
    requestBody: { [key: string]: string; };
}

export interface DeleteTrackedMediaRequest {
    requestBody: { [key: string]: number; };
}

export interface RequestMediaMergeRequest {
    mediaMergeRequest: MediaMergeRequest;
}

/**
 * 
 */
export class MediaProgressControllerApi extends runtime.BaseAPI {

    /**
     */
    async addNewMediaProgressRaw(requestParameters: AddNewMediaProgressRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<{ [key: string]: string; }>> {
        if (requestParameters['requestBody'] == null) {
            throw new runtime.RequiredError(
                'requestBody',
                'Required parameter "requestBody" was null or undefined when calling addNewMediaProgress().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/mediaProgresses/mediaProgress`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['requestBody'],
        }, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     */
    async addNewMediaProgress(requestParameters: AddNewMediaProgressRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<{ [key: string]: string; }> {
        const response = await this.addNewMediaProgressRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async deleteTrackedMediaRaw(requestParameters: DeleteTrackedMediaRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<{ [key: string]: string; }>> {
        if (requestParameters['requestBody'] == null) {
            throw new runtime.RequiredError(
                'requestBody',
                'Required parameter "requestBody" was null or undefined when calling deleteTrackedMedia().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/mediaProgresses/deleteTrackedMedia`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['requestBody'],
        }, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     */
    async deleteTrackedMedia(requestParameters: DeleteTrackedMediaRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<{ [key: string]: string; }> {
        const response = await this.deleteTrackedMediaRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async requestMediaMergeRaw(requestParameters: RequestMediaMergeRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<{ [key: string]: string; }>> {
        if (requestParameters['mediaMergeRequest'] == null) {
            throw new runtime.RequiredError(
                'mediaMergeRequest',
                'Required parameter "mediaMergeRequest" was null or undefined when calling requestMediaMerge().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/mediaProgresses/requestMediaMerge`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: MediaMergeRequestToJSON(requestParameters['mediaMergeRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     */
    async requestMediaMerge(requestParameters: RequestMediaMergeRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<{ [key: string]: string; }> {
        const response = await this.requestMediaMergeRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
