/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  MediaSiteDto,
} from '../models/index';
import {
    MediaSiteDtoFromJSON,
    MediaSiteDtoToJSON,
} from '../models/index';

export interface GetMediaSitesRequest {
    siteStatus?: string;
}

export interface UpdateMediaSiteRequest {
    mediaSiteDto: MediaSiteDto;
}

/**
 * 
 */
export class MediaSitesControllerApi extends runtime.BaseAPI {

    /**
     */
    async getMediaSitesRaw(requestParameters: GetMediaSitesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<MediaSiteDto>>> {
        const queryParameters: any = {};

        if (requestParameters['siteStatus'] != null) {
            queryParameters['siteStatus'] = requestParameters['siteStatus'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/mediaSites/getMediaSites`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(MediaSiteDtoFromJSON));
    }

    /**
     */
    async getMediaSites(requestParameters: GetMediaSitesRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<MediaSiteDto>> {
        const response = await this.getMediaSitesRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async updateMediaSiteRaw(requestParameters: UpdateMediaSiteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<MediaSiteDto>> {
        if (requestParameters['mediaSiteDto'] == null) {
            throw new runtime.RequiredError(
                'mediaSiteDto',
                'Required parameter "mediaSiteDto" was null or undefined when calling updateMediaSite().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/mediaSites/updateMediaSite`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: MediaSiteDtoToJSON(requestParameters['mediaSiteDto']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => MediaSiteDtoFromJSON(jsonValue));
    }

    /**
     */
    async updateMediaSite(requestParameters: UpdateMediaSiteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<MediaSiteDto> {
        const response = await this.updateMediaSiteRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
