/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  AddMediaProgressRequest,
  DeleteTrackedMediaRequest,
  MediaMergeRequest,
  MessageResponse,
} from '../models/index';
import {
    AddMediaProgressRequestFromJSON,
    AddMediaProgressRequestToJSON,
    DeleteTrackedMediaRequestFromJSON,
    DeleteTrackedMediaRequestToJSON,
    MediaMergeRequestFromJSON,
    MediaMergeRequestToJSON,
    MessageResponseFromJSON,
    MessageResponseToJSON,
} from '../models/index';

export interface AddNewMediaProgressRequest {
    addMediaProgressRequest: AddMediaProgressRequest;
}

export interface DeleteTrackedMediaOperationRequest {
    deleteTrackedMediaRequest: DeleteTrackedMediaRequest;
}

export interface RequestMediaMergeRequest {
    mediaMergeRequest: MediaMergeRequest;
}

/**
 * 
 */
export class MediaProgressControllerApi extends runtime.BaseAPI {

    /**
     */
    async addNewMediaProgressRaw(requestParameters: AddNewMediaProgressRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<MessageResponse>> {
        if (requestParameters['addMediaProgressRequest'] == null) {
            throw new runtime.RequiredError(
                'addMediaProgressRequest',
                'Required parameter "addMediaProgressRequest" was null or undefined when calling addNewMediaProgress().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/mediaProgresses/mediaProgress`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: AddMediaProgressRequestToJSON(requestParameters['addMediaProgressRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => MessageResponseFromJSON(jsonValue));
    }

    /**
     */
    async addNewMediaProgress(requestParameters: AddNewMediaProgressRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<MessageResponse> {
        const response = await this.addNewMediaProgressRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async deleteTrackedMediaRaw(requestParameters: DeleteTrackedMediaOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<MessageResponse>> {
        if (requestParameters['deleteTrackedMediaRequest'] == null) {
            throw new runtime.RequiredError(
                'deleteTrackedMediaRequest',
                'Required parameter "deleteTrackedMediaRequest" was null or undefined when calling deleteTrackedMedia().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/mediaProgresses/deleteTrackedMedia`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: DeleteTrackedMediaRequestToJSON(requestParameters['deleteTrackedMediaRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => MessageResponseFromJSON(jsonValue));
    }

    /**
     */
    async deleteTrackedMedia(requestParameters: DeleteTrackedMediaOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<MessageResponse> {
        const response = await this.deleteTrackedMediaRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async requestMediaMergeRaw(requestParameters: RequestMediaMergeRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<MessageResponse>> {
        if (requestParameters['mediaMergeRequest'] == null) {
            throw new runtime.RequiredError(
                'mediaMergeRequest',
                'Required parameter "mediaMergeRequest" was null or undefined when calling requestMediaMerge().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/mediaProgresses/requestMediaMerge`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: MediaMergeRequestToJSON(requestParameters['mediaMergeRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => MessageResponseFromJSON(jsonValue));
    }

    /**
     */
    async requestMediaMerge(requestParameters: RequestMediaMergeRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<MessageResponse> {
        const response = await this.requestMediaMergeRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
