/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  MessageResponse,
} from '../models/index';
import {
    MessageResponseFromJSON,
    MessageResponseToJSON,
} from '../models/index';

/**
 * 
 */
export class MediaProgressUserRequestControllerApi extends runtime.BaseAPI {

    /**
     */
    async getMediaProgressUserRequestsRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<object>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/mediaProgressUserRequests`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     */
    async getMediaProgressUserRequests(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<object> {
        const response = await this.getMediaProgressUserRequestsRaw(initOverrides);
        return await response.value();
    }

    /**
     */
    async retryProgressRequestsRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<MessageResponse>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/mediaProgressUserRequests/retryProgressRequests`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => MessageResponseFromJSON(jsonValue));
    }

    /**
     */
    async retryProgressRequests(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<MessageResponse> {
        const response = await this.retryProgressRequestsRaw(initOverrides);
        return await response.value();
    }

}
