/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  MediaDto,
  MediaWithProgressDto,
  MediaWithProgressesAndSitesDto,
} from '../models/index';
import {
    MediaDtoFromJSON,
    MediaDtoToJSON,
    MediaWithProgressDtoFromJSON,
    MediaWithProgressDtoToJSON,
    MediaWithProgressesAndSitesDtoFromJSON,
    MediaWithProgressesAndSitesDtoToJSON,
} from '../models/index';

export interface GetMediaWithAllProgressesRequest {
    mediaId: number;
}

/**
 * 
 */
export class MediaControllerApi extends runtime.BaseAPI {

    /**
     */
    async getMediaRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<MediaDto>>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/medias`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(MediaDtoFromJSON));
    }

    /**
     */
    async getMedia(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<MediaDto>> {
        const response = await this.getMediaRaw(initOverrides);
        return await response.value();
    }

    /**
     */
    async getMediaWithAllProgressesRaw(requestParameters: GetMediaWithAllProgressesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<MediaWithProgressesAndSitesDto>> {
        if (requestParameters['mediaId'] == null) {
            throw new runtime.RequiredError(
                'mediaId',
                'Required parameter "mediaId" was null or undefined when calling getMediaWithAllProgresses().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/medias/{mediaId}`;
        urlPath = urlPath.replace(`{${"mediaId"}}`, encodeURIComponent(String(requestParameters['mediaId'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => MediaWithProgressesAndSitesDtoFromJSON(jsonValue));
    }

    /**
     */
    async getMediaWithAllProgresses(requestParameters: GetMediaWithAllProgressesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<MediaWithProgressesAndSitesDto> {
        const response = await this.getMediaWithAllProgressesRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async getMyRecentMediaRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<MediaWithProgressDto>>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/medias/recent`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(MediaWithProgressDtoFromJSON));
    }

    /**
     */
    async getMyRecentMedia(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<MediaWithProgressDto>> {
        const response = await this.getMyRecentMediaRaw(initOverrides);
        return await response.value();
    }

}
