/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  UserNotificationListDto,
} from '../models/index';
import {
    UserNotificationListDtoFromJSON,
    UserNotificationListDtoToJSON,
} from '../models/index';

/**
 * 
 */
export class NotificationControllerApi extends runtime.BaseAPI {

    /**
     */
    async getNotificationsRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<UserNotificationListDto>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/notification/getNotifications`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => UserNotificationListDtoFromJSON(jsonValue));
    }

    /**
     */
    async getNotifications(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<UserNotificationListDto> {
        const response = await this.getNotificationsRaw(initOverrides);
        return await response.value();
    }

}
