/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';

export interface GetProgressAnalyticsRequest {
    timePeriod?: string;
}

/**
 * 
 */
export class ProgressAnalyticsControllerApi extends runtime.BaseAPI {

    /**
     */
    async getProgressAnalyticsRaw(requestParameters: GetProgressAnalyticsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<object>> {
        const queryParameters: any = {};

        if (requestParameters['timePeriod'] != null) {
            queryParameters['timePeriod'] = requestParameters['timePeriod'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/progressAnalytics`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     */
    async getProgressAnalytics(requestParameters: GetProgressAnalyticsRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<object> {
        const response = await this.getProgressAnalyticsRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
