/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  AddUserSubmissionRequest,
  MessageResponse,
} from '../models/index';
import {
    AddUserSubmissionRequestFromJSON,
    AddUserSubmissionRequestToJSON,
    MessageResponseFromJSON,
    MessageResponseToJSON,
} from '../models/index';

export interface AddUserSubmissionOperationRequest {
    addUserSubmissionRequest: AddUserSubmissionRequest;
}

/**
 * 
 */
export class UserSubmissionControllerApi extends runtime.BaseAPI {

    /**
     */
    async addUserSubmissionRaw(requestParameters: AddUserSubmissionOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<MessageResponse>> {
        if (requestParameters['addUserSubmissionRequest'] == null) {
            throw new runtime.RequiredError(
                'addUserSubmissionRequest',
                'Required parameter "addUserSubmissionRequest" was null or undefined when calling addUserSubmission().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/userSubmission/addUserSubmission`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: AddUserSubmissionRequestToJSON(requestParameters['addUserSubmissionRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => MessageResponseFromJSON(jsonValue));
    }

    /**
     */
    async addUserSubmission(requestParameters: AddUserSubmissionOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<MessageResponse> {
        const response = await this.addUserSubmissionRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async getMyUserSubmissionsRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<object>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/userSubmission/getMyUserSubmissions`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     */
    async getMyUserSubmissions(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<object> {
        const response = await this.getMyUserSubmissionsRaw(initOverrides);
        return await response.value();
    }

    /**
     */
    async getUserSubmissionsRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<object>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/userSubmission/getUserSubmissions`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     */
    async getUserSubmissions(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<object> {
        const response = await this.getUserSubmissionsRaw(initOverrides);
        return await response.value();
    }

}
